language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - os: osx
    osx_image: xcode7.2
    compiler: clang
install:
- cd $TRAVIS_BUILD_DIR/../
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x $TRAVIS_BUILD_DIR/getlinuxdeps.sh
  && $TRAVIS_BUILD_DIR/getlinuxdeps.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x $TRAVIS_BUILD_DIR/getosxdeps.sh
  && $TRAVIS_BUILD_DIR/getosxdeps.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/qt5/bin;
  fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ARMA_HDF5_INCLUDE_DIR=/usr/local/opt/hdf5/include;
  fi
- mkdir $TRAVIS_BUILD_DIR/../build && cd $TRAVIS_BUILD_DIR/../build
- qmake $TRAVIS_BUILD_DIR/buildall.pro
- make
after_success:
- export BUILD_DIR=$TRAVIS_BUILD_DIR/../build
- export LIB_DIR=$TRAVIS_BUILD_DIR/..
- export SRC_DIR=$TRAVIS_BUILD_DIR
- export PKG_DIR=$TRAVIS_BUILD_DIR/package
- mkdir $PKG_DIR
- export PKG_NAME=Vespucci_1.0.0-$TRAVIS_BUILD_NUMBER
- if [[ "TRAVIS_OS_NAME" == "osx" ]]; then export $OUT_PKG = $PKG_DIR/$PKG_NAME.dmg;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r $BUILD_DIR/Vespucci/Vespucci.app
  $TRAVIS_BUILD_DIR/../; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DEPLOY_DIR=$TRAVIS_BUILD_DIR/../Vespucci.app;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x $TRAVIS_BUILD_DIR/deploymac.sh
  && $TRAVIS_BUILD_DIR/deploymac.sh $SRC_DIR $BUILD_DIR $DEPLOY_DIR $LIB_DIR; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x $TRAVIS_BUILD_DIR/createdmg.sh
  && $TRAVIS_BUILD_DIR/createdmg.sh $DEPLOY_DIR $OUT_PKG $SRC_DIR; fi
- if [[ "TRAVIS_OS_NAME" == "linux" ]]; then export $OUT_PKG=$PKG_DIR/$PKG_NAME.tar.gz;
  fi
- if [[ "TRAVIS_OS_NAME" == "linux" ]]; then export DEPLOY_DIR=$TRAVIS_BUILD_DIR/Vespucci_$TRAVIS_COMMIT
  && mkdir DEPLOY_DIR; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x $TRAVIS_BUILD_DIR/deploylinux.sh
  && $TRAVIS_BUILD_DIR/deploylinux.sh $SRC_DIR $BUILD_DIR $DEPLOY_DIR $LIB_DIR; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x $TRAVIS_BUILD_DIR/createtarball.sh
  && $TRAVIS_BUILD_DIR/createtarball.sh $DEPLOY_DIR $OUT_PKG $SRC_DIR; fi
deploy:
  skip_cleanup: true
  provider: bintray
  file: $TRAVIS_BUILD_DIR/deploybintray.json
  user: dpfoose
  key: 
    secure: FbN+fh+xz3EspbAQP832Cpsf72BmObn92YQtISBiQq3tX3B+mknPIQfsNKf3KmRnhly/8uAuJzjZAK3C0iZ/JYzckmwO+VyF8k01oh2SRGy3xuwzQirBowOcRUMbjwBnQRnP0T3cOFsWHbcvZQmzTexsISK8lO184UXo6a1miRBpaT3cCffds4KvVQL0YtmTjsV4KZwLeH0j6bhtQxujeGeYSxz8LOhxMU/ve2j2NPbiMLXfNiYRwkX2XB3dLxnHIUHvgo63SQlYQnH5y9EI3CnfzUMhzMjyn3NWhE2AcH26sg2fgSd8JU0mw6Y7wzdXYBLhK+rVtB+p3cot3a7iSvL1QLDinfy0kCpWnWhq3GKHVxOlbvnKCByqGsX1yeguvdoIznizIO/7zYMfpePb4P44H4OYI1imdigPGEfehuAYXyVEdydYB08GKIUm1D1CWDAfxwUYsxTQWXwh1F0DirL7qpSezYS7SfSzSO5TpCQLitS3OcoY5pxv98e0i0q89PKE76AipvmcoAZON6yYHh/213bqj/IrC+CcN6UbnGk2S/+daOdA2gHxCiDywbeZPfvFNjppCX7ae6/aU/cf/SimZ0kgggUbcZX+iBsbJ29QFMl1IOiv6CAauYcXTQA8uEN6uBLzcvpGTTxkQVCxEhzaqdVxHKRrc8W+hT7uOUI=
