language: cpp
sudo: false
compiler:
    - gcc
addons:
    apt:
      sources:
          - boost-latest
          - ubuntu-sdk-team
          - ubuntu-toolchain-r-test
      packages:
          - g++-4.8
          - qt5-qmake 
          - qtbase5-dev
          - qtdeclarative5-dev
          - libqt5webkit5-dev
          - libsqlite3-dev
          - libqt5svg5-dev
          - libhdf5-serial-dev
          - libarpack2-dev
          - libxml2-dev
          - libboost1.55-dev
          - libboost-math1.55-dev
          - libboost-program-options1.55-dev
          - libboost-test1.55-dev
          - libboost-random1.55-dev
          - libcminpack-dev

before_install:
    - export CXX="g++-4.8"
    - g++ --version
    - mkdir $HOME/depts
    - mkdir $HOME/depts/include
    - mkdir $HOME/depts/bin
    - mkdir $HOME/depts/lib
    - mkdir $HOME/depts/share
    - wget http://iweb.dl.sourceforge.net/project/arma/armadillo-6.200.3.tar.gz
    - tar -xf armadillo-6.200.3.tar.gz
    - cd armadillo-6.200.3
    - ./configure -DINSTALL_LIB_DIR=$HOME/depts/lib -DINSTALL_INCLUDE_DIR=$HOME/depts/include -DINSTALL_DATA_DIR=$HOME/depts/share -DINSTALL_BIN_DIR=$HOME/depts/bin && make && make install
    - cd ../
    - wget http://mlpack.org/files/mlpack-1.0.12.tar.gz
    - tar -xf mlpack-1.0.12.tar.gz
    - cd mlpack-1.0.12 && mkdir build && cd build
    - cmake -DDEBUG=OFF -DPROFILE=OFF -DBOOST_INCLUDEDIR=/usr/include/boost -DCMAKE_INSTALL_PREFIX=$HOME/depts ../
    - make mlpack >/dev/null && make install >/dev/null
    - cd ../../
    - git clone https://github.com/VespucciProject/Vespucci-QCP.git
    - cd Vespucci-QCP
    - qmake -qt=qt5 && make && make install
    - cd ../
    - /usr/include/cminpack-1
    - /usr/include/cminpack-1/cminpack.h

script:
    - mkdir build-VespucciLibrary && cd build-VespucciLibrary
    - qmake -qt=qt5 ../Library/VespucciLibrary.pro && make
    - cd ../ && mkdir build-Vespucci && cd build-Vespucci
    - qmake -qt=qt5 ../Vespucci.pro && make
