language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode7.2
      compiler: clang


before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x getlinuxdeps.sh && ./getlinuxdeps.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x getosxdeps.sh && ./getosxdeps.sh; fi

script:
    - mkdir ../build && cd ../build
    - qmake ../buildall.pro
    - make
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x copylinuxlibs.sh && ./copylinuxlibs.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x copymaclibs.sh && ./copymaclibs.sh; fi

