language: cpp
sudo: false
compiler:
    - gcc
addons:
    apt:
      sources:
          - boost-latest
          - ubuntu-sdk-team
      packages:
          - qt5-qmake 
          - qtbase5-dev
          - qtdeclarative5-dev
          - libqt5webkit5-dev
          - libsqlite3-dev
          - libqt5svg5-dev
          - libhdf5-serial-dev
          - libarpack2-dev
          - libsuperlu3-dev
          - libxml2-dev
          - libboost1.55-dev
          - libboost-math1.55-dev
          - libboost-program-options1.55-dev
          - libboost-test1.55-dev
          - libboost-random1.55-dev
          - libcminpack-dev

before_install:
    - wget http://iweb.dl.sourceforge.net/project/arma/armadillo-6.200.3.tar.gz
    - tar -xf armadillo-6.200.3.tar.gz
    - cd armadillo-6.200.3
    - ./configure -DINSTALL_LIB_DIR=~/depts/lib -DINSTALL_INCLUDE_DIR=~/depts/include -DINSTALL_DATA_DIR=~/depts/share -DINSTALL_BIN_DIR=~/depts/bin && make && make install
    - cd ../
    - wget http://mlpack.org/files/mlpack-1.0.12.tar.gz
    - tar -xf mlpack-1.0.12.tar.gz
    - cd mlpack-1.0.12 && mkdir build && cd build
    - cmake -DDEBUG=OFF -DPROFILE=OFF -DCMAKE_INSTALL_PREFIX=~/depts ../
    - make mlpack >/dev/null && make install >/dev/null
    - cd ../../
    - git clone https://github.com/VespucciProject/Vespucci-QCP.git
    - cd Vespucci-QCP
    - qmake -qt=qt5 && make && make install
    - cd ../

script:
    - mkdir ~/build-VespucciLibrary && cd ~/build-library
    - qmake -qt=qt5 ../Library/VespucciLibrary.pro
    - make
    - cd ~/build-Vespucci
    - qmake -qt=qt5 ../Vespucci.pro
