version: 1.0.{build}
image: Visual Studio 2015
clone_depth: 30
clone_folder: C:\Projects\Vespucci
cache: C:\Projects\Vespucci_dependencies
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

    set QTDIR=C:\Qt\5.6\msvc2015_64

    cd C:\Projects

    IF NOT EXIST C:\Projects\Vespucci_dependencies appveyor DownloadFile https://github.com/VespucciProject/Vespucci_dependencies/releases/download/1/Vespucci_dependencies_w64.7z

    IF NOT EXIST C:\Projects\Vespucci_dependencies 7z x Vespucci_dependencies_w64.7z -aoa > NUL

    set LIB_DIR=%CD%\Vespucci_dependencies


    mkdir build && cd build

    set BUILD_DIR=%CD%

    %QTDIR%\bin\qmake ..\Vespucci\buildall.pro

    nmake release


    set DEPLOYMENT_DIR=Vespucci-w64-build_%APPVEYOR_BUILD_NUMBER%

    mkdir %DEPLOYMENT_DIR%

    C:\Projects\Vespucci\deploywin.bat

    %QTDIR%\bin\windeployqt %DEPLOYMENT_DIR%\vespucci.exe

    7z a -tzip C:\Projects\Vespucci\Vespucci_w64_%APPVEYOR_BUILD_NUMBER%.zip %DEPLOYMENT_DIR%
test: off
artifacts:
- path: Vespucci_w64_$(appveyor_build_number).zip
  name: Vespucci_w64_$(appveyor_build_number).zip
- path: build_log_$(appveyor_build_number).zip
  name: build_log_$(appveyor_build_number).zip
deploy:
- provider: BinTray
  username: dpfoose
  api_key:
    secure: xJeROKVvw5l5QAfaHijL0+J7PKDG/QzvSV/aNpd0eZliEeQI1WWVP4T6FXmje1A3
  subject: vespucciproject
  repo: Vespucci_automated_builds
  package: Vespucci-w64-latest
  artifact: Vespucci_w64_$(appveyor_build_number).zip
  publish: true
  explode: false